blank_issues_enabled: true
contact_links:
  - name: New AVM Module Proposal ğŸ“
    url: https://aka.ms/AVM/ModuleProposal
    about: Want a new AVM Module to exist? Let us know!
  - name: New Bicep Child Module Proposal ğŸ—’ï¸
    url: https://aka.ms/AVM/???
    about: Want to publish the child module of a Bicep resource module? Let us know!
