name: "avm.platform.publish.tag"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The git tag of the module to publish."
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  job_publish_module_with_tag:
    runs-on: ubuntu-latest
    name: "Publish module with tag"
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ env.PUBLISH_CLIENT_ID }}
          tenant-id: ${{ env.PUBLISH_TENANT_ID }}
          subscription-id: ${{ env.PUBLISH_SUBSCRIPTION_ID }}

      # Adding a step to explicitly install the latest Bicep CLI because there is
      # always a delay in updating Bicep CLI in the job runner environments.
      - name: Install the latest Bicep CLI
        shell: bash
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          bicep --version

      - name: "Publish tagged module to public bicep registry"
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
            # Grouping task logs
            Write-Output '::group::Publish tagged module to public bicep registry'

            # Load used functions
            . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines'  'publish' 'Publish-ModuleFromTagToPBR.ps1')

            $functionInput = @{
              ModuleReleaseTagName = '${{ github.event.inputs.tag }}'
              PublicRegistryServer = ConvertTo-SecureString '${{ secrets.PUBLISH_REGISTRY_SERVER }}' -AsPlainText -Force
            }

            Write-Verbose "Invoke function with" -Verbose
            Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

            Publish-ModuleFromTagToPBR @functionInput -Verbose

            Write-Output '::endgroup::'