name: 'avm.platform.toggle-avm-workflows'

on:
  workflow_dispatch:
    inputs:
      workMode:
        type: choice
        description: "Enable or disable workflows"
        required: true
        options:
          - "enable"
          - "disable"
        default: "disable"
      includePattern:
        type: string
        description: "RegEx which workflows are included"
        required: false
        default: "avm\.(?:res|ptn)"
      excludePattern:
        type: string
        description: "RegEx which workflows are excluded"
        required: false
        default: "^$"

jobs:
  toggle-avm-workflows:
    if: github.repository != 'Azure/bicep-registry-modules'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - env:
          GH_TOKEN: ${{ github.token }}
        name: ${{ inputs.workMode }} AVM workflows
        shell: pwsh
        run: |
            $repo = "${{ github.repository_owner }}/${{ github.event.repository.name }}"
            $workflows = gh workflow list --repo $repo --all --json 'name,state,id' | ConvertFrom-Json -Depth 100
            $relevantWorkflows = $workflows | Where-Object {
                $_.name -match "${{ inputs.includePattern }}" -and $_.name -notmatch "${{ inputs.excludePattern }}"
            }

            foreach ($workflow in $relevantWorkflows) {
                if (("${{ inputs.workMode }}" -eq "disable" -and $workflow.state -eq 'active') -or ("${{ inputs.workMode }}" -eq "enable" -and $workflow.state -ne 'active'))
                {
                  Write-Verbose "${{ inputs.workMode }} $($workflow.name)" -Verbose
                  gh workflow ${{ inputs.workMode }} $workflow.id  --repo $repo
                }
            }
