name: On push run brm generate # fork only, optional

on:
  push:
    branches-ignore:
      - main
    paths:
      - modules/**/*.bicep
      - modules/**/*.sh
      - modules/**/metadata.json

jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      my-key: ${{ steps.my-key.outputs.defined }}
    steps:
      - id: my-key
        if: "${{ env.MY_KEY != '' }}"
        run: echo "defined=true" >> $GITHUB_OUTPUT
        env:
          MY_KEY: ${{ secrets.PAT }}

  get-module-to-validate:
    needs: [check-secret]
    if: needs.check-secret.outputs.my-key == 'true'
    uses: ./.github/workflows/get-changed-module.yml

  push-brm-generate:
    runs-on: ubuntu-latest
    needs: get-module-to-validate
    if: needs.get-module-to-validate.outputs.module_dir
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }} # A PAT must be used to re-trigger workflows after commit. This PAT should NOT have the workflow scope.

      # Adding a step to explicitly install the latest Bicep CLI because there is
      # always a delay in updating Bicep CLI in the job runner environments.
      - name: Install the latest Bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          bicep --version
      - uses: jungwinter/split@master
        id: branch
        with:
          msg: ${{ needs.get-module-to-validate.outputs.module_dir }}
          separator: "/"
          maxsplit: -1

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "${{ steps.branch.outputs._1 }}/${{ steps.branch.outputs._2 }}/"
          dry_run: true
          default_bump: false

      - name: Update Version
        if: steps.tag_version.outputs.release_type
        shell: bash
        env:
          OLD_VERSION: ${{ steps.tag_version.outputs.previous_version }}
          VERSION: ${{ steps.tag_version.outputs.new_version }}
          SAMPLEFOLDER_PATH: ${{ needs.get-module-to-validate.outputs.module_dir }}
          MODULE: "${{ steps.branch.outputs._1 }}/${{ steps.branch.outputs._2 }}"
        run: |
          cd $SAMPLEFOLDER_PATH
          NEW_VERSION=${VERSION%%-*}
          # The following sed command searches for the specified module in README.md and replaces its version number
          # (in formats X.Y.Z, X.Y, X, or a single lowercase letter) or adds a version number if it's not present.
          REGEX=$(echo "s|($MODULE:)([0-9]+(\.[0-9]+){0,2})?|\1$NEW_VERSION|")
          sed -ri "$REGEX" "README.md" || exit 1

      - name: Run brm generate
        env:
          SAMPLEFOLDER_PATH: ${{ needs.get-module-to-validate.outputs.module_dir }}
        run: |
          dotnet tool install --global Azure.Bicep.RegistryModuleTool

          cd $SAMPLEFOLDER_PATH
          brm generate

      - uses: EndBug/add-and-commit@v9
        with:
          message: Autogenerate Bicep Files
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: modules
